apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: instana-agent
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318

