apiVersion: v1
kind: Service
metadata:
  name: todoapi-service
  namespace: instana-agent
spec:
  type: NodePort
  selector:
    app: todoapi
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
